Update install

diff --git a/tools/install b/tools/install
--- a/tools/install
+++ b/tools/install
@@ -10,8 +10,11 @@ GH_USER="drliangjin"
 GH_REPO=".hammerspoon.d"
 GH_BRANCH="master"
 
-# Hammerspoon
+# Hammerspoon configuration dir
 HS_DIR="$HOME/${GH_REPO}"
+
+# Spoon Archives
+SPOON_ARC="https://github.com/Hammerspoon/Spoons/raw/master/Spoons"
 
 # symlink
 LINK_DIR="$HOME/.hammerspoon"
@@ -42,8 +45,10 @@ function brew_install() {
         echo " => unable to install "${formulae}" !"
         return 1
       else
-        echo "Installing "${formulae}"...done"
+        echo "Installing "${formulae}"...done "
       fi
+    else
+      echo "Installing "${formulae}"...skipped "
     fi
   fi
 }
@@ -59,8 +64,10 @@ function cask_install() {
         echo " => unable to install $formulae !"
         return 1
       else
-        echo "Installing $formulae...done"
+        echo "Installing $formulae...done "
       fi
+    else
+      echo "Installing "${formulae}"...skipped "
     fi
   fi
 }
@@ -69,36 +76,40 @@ function clone_config() {
   echo "Deploying Hammerspoon configuration..."
   git clone -q -b ${GH_BRANCH} https://github.com/${GH_USER}/${GH_REPO}.git && \
   ln -sf ${HS_DIR} ${LINK_DIR} && \
-  echo "Deploying Hammerspoon configuration...done"
+  echo "Deploying Hammerspoon configuration...done "
 }
 
 function download_spoon() {
   local spoon_name=$1
   if [[ ! -z "${spoon_name}" ]]; then
-    local spoon_url="https://github.com/Hammerspoon/Spoons/raw/master/Spoons/${spoon_name}.spoon.zip"
-    local spoon_dir="${HS_DIR}/Spoons"
+    local spoon_url="${SPOON_ARC}/${spoon_name}.spoon.zip"
+    local spoon_dir="${HS_DIR}/Spoons/${spoon_name}.spoon"
     echo "Downloading Spoon: ${spoon_name}..."
-    cd /tmp
-    curl -fsSLO "${spoon_url}"
-    mkdir -p "${spoon_dir}" && unzip -q "${spoon_name}.spoon.zip" -d "${spoon_dir}"
-    if [[ $? != 0 ]]; then
-      echo " => unable to download ${spoon_name} !"
-      return 1
+    if [[ ! -d "${spoon_dir}" ]]; then
+      cd /tmp
+      curl -fsSLO "${spoon_url}"
+      mkdir -p "${spoon_dir}" && unzip -q "${spoon_name}.spoon.zip" -d "${spoon_dir}"
+      if [[ $? != 0 ]]; then
+        echo " => unable to download ${spoon_name} !"
+        return 1
+      else
+        echo "Installing Spoon: ${spoon_name}...done "
+      fi
     else
-      echo "Installing Spoon: ${spoon_name}...done"
+      echo "Installing Spoon: ${spoon_name}...skipped "
     fi
   fi
 }
 
 function main() {
 
-  install_homebrew &&\
+  install_homebrew && \
   
-  brew_install lua &&\
+  brew_install lua && \
   
-  cask_install hammerspoon &&\
+  cask_install hammerspoon && \
   
-  clone_config &&\
+  clone_config && \
   
   download_spoon SpoonInstall
 }
